# Guitar Model Classification
## Import required Libraries

In [14]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC 
from sklearn.dummy import DummyClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.cross_validation import train_test_split

## Load Training Data

In [16]:
# Normalize Feature to a range between -1 and 1
scaler = preprocessing.MinMaxScaler(feature_range=(-1,1))

data = np.load("../data/acoustic_electric.npz")
features = scaler.fit_transform(data['features'])
labels = data['labels']
sources = data['sources']
classes = data['classes']

## Load Test Data

In [17]:
# testData = np.load("../data/bextract_single_test.npz")

# testFeatures = scaler.fit_transform(testData['features'])
# testLabels = testData['labels']
# testSources = testData['sources']

trainingData, testData, trainingLabels, testLabels =  train_test_split(features, labels, test_size=0.33, random_state=42)

In [18]:
len(testLabels)

33634

## Train Classifier

In [19]:
# model = KNeighborsClassifier(n_neighbors=1)
# model = GaussianNB()
model = SVC()
# model = DecisionTreeClassifier()
# model = DummyClassifier(strategy='most_frequent')

model.fit(trainingData, trainingLabels)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.0,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [20]:
model.predict([  1.27929687e-02,   1.31835938e-02,   1.26596590e-02,   7.09336326e-02,
  -7.52855180e+01,   5.84245664e+00,   2.57158601e+00,   1.93837656e+00,
   1.40690361e+00,   1.22374845e+00,   7.98509423e-01,   5.10000599e-01,
   1.93025722e-01,   2.29708432e-01,   4.74888412e-01,   4.73021053e-01,
   3.50734408e-01,   1.10575335e-06,   1.10659863e-06,   1.14047687e-06,
   1.24277493e-06,   1.29963961e-06,   1.32382605e-06,   1.31582928e-06,
   1.27870244e-06,   1.22787128e-06,   1.18585854e-06,   1.14826800e-06,
   1.11668611e-06 ,  1.18058787e+00,   1.51133210e+00,   1.76053509e+00,
   1.76053509e+00,   1.77782947e+00,   1.42303714e+00,   1.54456132e+00,
   1.98823100e+00,   1.94177757e+00,   2.04733266e+00,   2.03475350e+00,
   2.39271870e+00,   2.27689373e+00,   2.32564266e+00,   2.54447586e+00,
   2.70536416e+00,   2.95129839e+00,   3.02720345e+00,   3.27104313e+00,
   3.27883290e+00,   3.53770035e+00,   4.00783439e+00,   4.00096909e+00,
   4.14382477e+00 ,  4.23015745e+00,   4.46094417e+00,   8.18158910e-03,
   9.33371034e-03 ,  3.64011998e-02,   1.78140624e-02,   2.85128335e+00,
   1.67326483e+00,   7.87823208e-01,   5.13813528e-01,   5.86386529e-01,
   6.46039146e-01,   7.26708478e-01,   7.32690502e-01,   6.62268114e-01,
   4.07030624e-01,   4.50227853e-01,   5.48802281e-01,   3.83256435e-01,
   1.47670619e-06,   1.39875148e-06,   1.38175083e-06,   1.49441442e-06,
   1.58890397e-06,   1.66069116e-06,   1.70592498e-06,   1.71462394e-06,
   1.69563792e-06,   1.67900004e-06,   1.63078458e-06,   1.55766504e-06,
   1.25680901e-01,   4.64474163e-01,   2.23156486e-01,   2.23156486e-01,
   2.47901704e-01,   2.29319002e-01,   2.45194562e-01,   5.67014408e-01,
   5.55609358e-01,   5.90240936e-01,   5.83616982e-01,   6.07474593e-01,
   5.41573630e-01,   5.09196071e-01 ,  6.16319317e-01,   7.70159058e-01,
   7.63601911e-01,   6.76377600e-01,   8.05575067e-01,   6.55773988e-01,
   1.00927140e+00,   1.12344895e+00,   1.23117906e+00,   9.79102172e-01,
   9.87536057e-01,   1.03467680e+00])

array([ 1.])

## Predict Test Data

In [ ]:
model.score(testData, testLabels)

In [8]:
model.classes_

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.])

In [9]:
testLabels

array([ 7.,  8.,  3., ...,  3.,  3.,  7.])

In [10]:
trainingLabels

array([ 5.,  3.,  9., ...,  3.,  0.,  5.])